### ISSUE TITLE
Implementar sensação de movimento quando as linhas são desenhadas

### ISSUE THREAD

**Issue by ThalissonMelo** [ThalissonMelo/turtle#1]
É preciso fazer o array de pontos do update preencher vários pontos entre o inicio e o final da linha, também é necessário criar um delay no método draw para que ele não desenhe tão rápido

**Comment by guiaugusto** [comment]
Usando o deslocamento que você tinha mencionado anteriormente à mim, eu implementei a sensação de movimento de acordo com a speed da turtle (usando como base o material que você tinha me passado anteriormente). Com isso, a lógica de animação ficou limitada apenas à movimentos simples (do tipo `move`).

Aproveitei pra fazer uns refactors no método `update`, modularizando para que condição tenha um método de ação associado.
